sudo: false
language: node_js
node_js:
  - 17
env:
  global:
    - COVERALLS_PARALLEL=true
jobs:
  include:
    - script: COVERALLS_FLAG_NAME=test-1 make test-coveralls-1
    - script: COVERALLS_FLAG_NAME=test-2 make test-coveralls-2
    - script: npm install coveralls nyc --save-dev
notifications:
  webhooks: https://coveralls.io/webhook
after_success: npm run coverage
